tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "ldez/tap"
tap "bramstein/webfonttools"
tap "mongodb/brew"
tap "stripe/stripe-cli"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Command-line benchmark tool
brew "bench"
# GNU binary tools for native development
brew "binutils"
# Parser generator
brew "bison"
# Fish completion for brew-cask
brew "brew-cask-completion"
# Core application library for C
brew "glib"
# Color-highlighted diff(1) output
brew "colordiff"
# Dependency Manager for PHP
brew "composer"
# GNU File, Shell, and Text utilities
brew "coreutils"
# C library implementing the SSH2 protocol
brew "libssh2"
# Open source suite of directory software
brew "openldap"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# File comparison utilities
brew "diffutils"
# Load/unload environment variables based on $PWD
brew "direnv"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Create Docker hosts locally and on cloud providers
brew "docker-machine"
# Convert text between DOS, UNIX, and Mac formats
brew "dos2unix"
# Classic UNIX line editor
brew "ed"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Library to load and enumerate PKCS#11 modules
brew "p11-kit"
# GNU Emacs text editor
brew "emacs"
# Modern replacement for 'ls'
brew "exa"
# OpenType text shaping engine
brew "harfbuzz"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Utility to determine file types
brew "file-formula"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Fast Lexical Analyzer, generates Scanners (tokenizers)
brew "flex"
# Fast and simple Node.js version manager
brew "fnm"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# GNU debugger
brew "gdb"
# GitHub command-line tool
brew "gh"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Command-line utility for uploading Gists
brew "gist"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Git extension for versioning large files
brew "git-lfs"
# C code prettifier
brew "gnu-indent"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# GNU implementation of which utility
brew "gnu-which"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Apply a diff file to an original
brew "gpatch"
# Colorize logfiles and command output
brew "grc"
# GNU grep, egrep and fgrep
brew "grep"
# Popular GNU data compression program
brew "gzip"
# Improved top (interactive process viewer)
brew "htop"
# Configurable static site generator
brew "hugo"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Pager program similar to more
brew "less"
# Version of the SSL/TLS protocol forked from OpenSSL
brew "libressl"
# Swiss Army Knife for macOS
brew "m-cli"
# Macro processing language
brew "m4"
# Create Mac OS VPNs programmatically
brew "macosvpn"
# Utility for directing compilation
brew "make"
# Mac App Store command-line interface
brew "mas"
# Java-based project management
brew "maven"
# Sign files & verify signatures. Works with signify in OpenBSD
brew "minisign"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Interactive cheatsheet tool for the command-line
brew "navi"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Development kit for the Java programming language
brew "openjdk@11"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Cryptography and SSL/TLS Toolkit
brew "openssl"
# Programming language prerequisites and package managers
brew "libyaml" # should come after openssl
# Highly capable, feature-rich programming language
brew "perl"
# General-purpose scripting language
brew "php"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Utility that provides fast incremental file transfer
brew "rsync"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Safe, concurrent, practical language
brew "rustup"
# Build tool for Scala projects
brew "sbt"
# Terminal multiplexer with VT100/ANSI terminal emulation
brew "screen"
# Generate ASCII art with terminal, shell, and OS info
brew "screenfetch"
# Cross-shell prompt for astronauts
brew "starship"
# Strong open-source chess engine
brew "stockfish"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Version control system designed to be a better CVS
brew "subversion"
# Required for roboto font
brew "svn"
# Open source continuous file synchronization application
brew "syncthing"
# Code-search similar to ack
brew "the_silver_searcher"
# Simplified and community-driven man pages
brew "tldr"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extraction utility for .zip compressed archives
brew "unzip"
# Vi 'workalike' with many additional features
brew "vim"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Display word differences between text files
brew "wdiff"
# Internet file retriever
brew "wget"
# Show the current WiFi network password
brew "wifi-password"
# Utilities to create and convert Web Open Font File (WOFF) files
brew "woff2"
# yarn
brew "yarn"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Zsh shell
brew "zsh"
# Bash script to audit and fix macOS Catalina (10.15.x) security settings
brew "0xmachos/mosl/mosl"
# Convert existing TrueType/OpenType fonts to WOFF format
brew "bramstein/webfonttools/sfnt2woff"
# WOFF utilities with Zopfli compression
brew "bramstein/webfonttools/sfnt2woff-zopfli"
# GitHub Changelog Generator
brew "ldez/tap/gcg"
# High-performance, schema-free, document-oriented database
brew "mongodb/brew/mongodb-community"
# Stripe CLI utility
brew "stripe/stripe-cli/stripe"
# Inspect application bundles
cask "apparency"
# Screen saver based on animations presented during Apple Special Event Brooklyn
cask "brooklyn"
# Fonts
cask "font-awesome-terminal-fonts"
cask "font-hack"
cask "font-fira-code"
cask "font-fira-mono"
# Icon set and toolkit
cask "font-fontawesome"
cask "font-roboto-mono"
cask "font-source-code-pro"
# Penetration testing framework
cask "metasploit"
# QuickLook plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# QuickLook generator for Markdown files
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
# Application for inspecting installer packages
cask "suspicious-package"
